[phases.install]
cmds = [
  "if [ -d 'flask-backend' ]; then cd flask-backend && python3 -m pip install -r requirements.txt; else echo 'Error: flask-backend directory not found' && exit 1; fi",
  "if [ -d 'react-frontend' ]; then cd react-frontend && npm install; else echo 'Error: react-frontend directory not found' && exit 1; fi"
]

[phases.build]
cmds = [
  "if [ -d 'react-frontend' ]; then cd react-frontend && npm run build; else echo 'Error: react-frontend directory not found' && exit 1; fi"
]

[start]
cmd = "cd flask-backend && python3 app.py"
