[phases.setup]
nixPkgs = ["python311Full", "nodejs_20"]

[phases.install]
cmds = [
  "cd flask-backend && python3 -m pip install --upgrade pip",
  "cd flask-backend && python3 -m pip install -r requirements.txt",
  "cd react-frontend && npm install"
]

[phases.build]
cmds = [
  "cd react-frontend && npm run build"
]

[start]
cmd = "cd flask-backend && python3 app.py"
