[phases.setup]
nixPkgs = ["python311", "nodejs_20"]

[phases.install]
cmds = [
  "cd flask-backend",
  "cd react-frontend && npm install"
]

[phases.build]
cmds = [
  "cd react-frontend && npm run build"
]

[start]
cmd = "cd flask-backend && python app.py"
