[phases.setup]
nixPkgs = [
  "python311",
  "python311Packages.pip",
  "nodejs_20"
]

[phases.install]
cmds = [
  "python3 -m venv /app/venv", # Create venv in /app
  "source /app/venv/bin/activate",
  "pip3 install --no-cache-dir --break-system-packages -r /app/flask-backend/requirements.txt", # Install with --break-system-packages and no cache
  "npm install --prefix /app/react-frontend" # Correct npm install
]

[phases.build]
cmds = [
  "npm run build --prefix /app/react-frontend" # Correct npm build
]

[start]
cmd = "source /app/venv/bin/activate && python /app/flask-backend/app.py" # Activate, then run
